[package]
name = "hack_chat_types"
version = "0.1.0"
authors = ["MinusGix <minusgix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For parsing and forming json messages
json = "0.12.4"
