[package]
name = "hack_chat_types"
version = "0.1.0"
authors = ["MinusGix <minusgix@gmail.com>"]
edition = "2018"

[features]
default = []
json_parsing = ["json"]

[dependencies]
# For parsing and forming json messages
json = { version = "0.12.4", optional = true }
